config/routes.rb
Bambooweek::Application.routes.draw do
  root :to => 'items#index'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resource :cart, :only => [:show] do 
    post :put_into
    post 'remove_from/:item_id' => 'carts#remove_from', :as => :remove_from
  end

  resource :order, :only => [:show, :create]

  resources :items, :only => [:index, :show]

end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :picture, VenusUploader
  has_many :order_itemships, :dependent => :destroy
  has_many :orders, :through => :order_itemships
  attr_accessible :description, :name, :picture, :price, :picture_cache, :remove_picture
  auto_html_for :description do
    html_escape
    image
    youtube(:width => 400, :height => 250)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_itemships, :dependent => :destroy
  has_many :items, :through => :order_itemships
  attr_accessible :email, :mobile, :name, :stid, :item_ids, :draw_date, :note

  validates_presence_of :name, :email, :mobile, :draw_date
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_format_of :mobile, :with => /^\d*$/
  validates :draw_date, :inclusion => {:in => [515, 516], :message => "%{value} is not a valid draw date"}

  def total_price
    total = 0
    self.order_itemships.each do |o_i|
      total += o_i.count.to_i * o_i.item.price.to_i
    end
    return total
  end
end

app/models/order_itemship.rb
class OrderItemship < ActiveRecord::Base
  attr_accessible :count, :item_id, :order_id
  belongs_to :order
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
# -*- encoding : utf-8 -*-
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
    def reject_create_order
      flash[:notice] = 'Ooops! 預購已經截止囉，直接去竹塹週買吧！'
      redirect_to root_path
      return
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :find_cart
  def show
  end

  def put_into
    reject_create_order
    return

    @item = Item.find(params[:item_id])

    item_info = {
      :name => @item.name,
      :count => params[:count].to_i.abs,
      :price => @item.price
    }

    @cart[@item.id] = item_info
    session[:cart] = @cart

    redirect_to cart_path
  end

  def remove_from
    reject_create_order
    return

    @cart.delete(params[:item_id].to_i) if @cart.include? params[:item_id].to_i
    session[:cart] = @cart

    redirect_to cart_path
  end

  private
    def find_cart
      @cart = session[:cart] || {}
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    unless params[:mobile].nil?
      mobile = params[:mobile]
      @orders = Order.where('mobile = ?', mobile)
    else
      @orders = []
    end
  end

  def create
    reject_create_order
    return

    items_info = params[:order][:items_info].split(',').map {|x| x.split(':')}
    params[:order].delete(:items_info)
    @order = Order.new(params[:order])

    items_info.each do |item|
      o_i = OrderItemship.new(:item_id =>item[0], :count => item[1])
      @order.order_itemships << o_i
    end
    
    if @order.save
      flash[:notice] = '訂單建立成功'
      session[:cart] = {}
      redirect_to root_path
    else
      flash[:notice] = '訂單建立失敗'
      redirect_to cart_path
    end
  end
end

app/helpers/application_helper.rb
# -*- encoding : utf-8 -*-
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/carts/show.html.erb
<div class="page-header">
  <h1>購物車</h1>
</div>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>名稱</th>
    <th>數量</th>
    <th>單價</th>
    <th>小計</th>
    <th></th>
    <th>總價</th>
  </tr>

  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>
      <%= @cart.map {|_, info| info[:price].to_i * info[:count].to_i }.sum %>
    </td>
  </tr>
<% @cart.each do |id, info| %>
  <tr>
    <td><%= link_to info[:name], item_path(id) %></td>
    <td><%= info[:count] %></td>
    <td><%= info[:price] %></td>
    <td><%= info[:price].to_i * info[:count].to_i %></td>
    <td><%= button_to '刪除', remove_from_cart_path(:item_id => id), :class => 'btn btn-danger btn-mini' %></td>
    <td></td>
  </tr>
<% end %>
</table>
<%= simple_form_for(Order.new, :url => order_path) do |f| %>
  <%= f.input :name, :label => '姓名' %>
  <%= f.input :mobile, :label => '手機' %>
  <%= f.input :email, :placeholder => '請台大學生填寫台大信箱' %>
  <%= f.input :draw_date, :collection => [['5/15', 515], ['5/16', 516]], :selected => 515 %>
  <%= f.input :note, :placeholder => '對於竹塹周網路預購，以及繳費、取貨有任何疑問，歡迎提出，我們會神出鬼沒的以電子郵件的方式回覆您', :input_html => { :rows => 10 } %>
  <%= f.input :items_info, :as => :hidden, :input_html => { :value => (@cart.map {|i,info| [i, info[:count]].join(':')}).join(',') } %>
  <%= f.button :submit, '建立訂單' %>
<% end %>

app/views/items/index.html.erb
<div class="page-header text-center">
  <span class="pull-right">
    2013/5/5, 24:00預購截止
  </span>
  <h1>
    2013台大竹塹週 快來吃我吧
  </h1>
</div>
<div class="well span12 text-center">
  <h1>
    <%= flash[:notice] %>
  </h1>
  <ul class="thumbnails">
    <% @items.each do |item| %>
      <li class="span4">
      <div class="thumbnail">
        <div class="caption">
          <h3><%= item.name %></h3>
          <p><%= image_tag(item.picture_url(:medium)) if item.picture? %></p>
          <p><%= link_to '查看', item_path(item), class: 'btn btn-primary', style: 'float: bottom' %></p>
        </div>
      </div>
      </li>
    <% end %>
  </ul>
  <%= paginate @items %>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="span4">
    <p><%= image_tag(@item.picture_url(:medium)) if @item.picture? %></p>
  </div>
  <div class="span8">
    <%= form_tag put_into_cart_path, :method => :post, :class => 'form-inline' do %>
      <span class="badge badge-info" style="margin-right: 10px"> 價格: <%= @item.price %> </span>
      <span style="margin-right: 10px"> <%= label_tag 'count', '數量' %> </span>
      <span style="margin-right: 10px"> <%= number_field_tag 'count', 1, :class => 'input-mini' %> </span>
      <%= hidden_field_tag 'item_id', @item.id %>
        <%= submit_tag '加入購物車', :class => 'btn btn-action' %>
    <% end %>
    <p><%= @item.description_html %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>竹塹週預購網站</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    <%= yield :header %>
    <%= stylesheet_link_tag    "application", :media => "all" %>

    <%#= javascript_include_tag "templates/admin_panel" %>
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= "%s_%s" % [controller_name, action_name] %>" class="<%= controller_name %> <%= action_name %>">

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
              <%= link_to "/" do %>
                台大竹塹週
              <% end %>
              </li>
              <li>
              <%= link_to page_path('notice') do %>
                預購須知
              <% end %>
              </li>
              <li>
              <%= link_to "https://www.facebook.com/EatMe2013BambooWeek", target: :_blank do %>
                聯絡我們
              <% end %>
              </li>
              <li>
                <div class="fb-like" data-href="http://week.ntubamboo.com/" data-send="true" data-layout="button_count" data-width="450" data-show-faces="false" data-font="arial" style="margin: 12px;"></div>
              </li>
            </ul>
            <ul class="nav pull-right">
              <li>
              <%= link_to cart_path do %>
                查看購物車
              <% end %>
              </li>
              <li>
              <%= link_to order_path do %>
                訂單查詢
              <% end %>
              </li>
            </ul>
            <ul class="nav">
              <li class="dropdown">

              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
      <script type="text/javascript"><!--
        google_ad_client = "ca-pub-0529325452859575";
        /* bambooweek */
        google_ad_slot = "2524337728";
        google_ad_width = 728;
        google_ad_height = 90;
        //-->
      </script>
      <script type="text/javascript"
        src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
      </script>
      <p>&copy; </p>
      </footer>

    </div><!--/.fluid-container-->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/zh_TW/all.js#xfbml=1&appId=225830524119019";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
  </body>
</html>

app/views/orders/show.html.erb
<div class="page-header text-center">
  <h1>訂單查詢</h1>
  <%= form_tag order_path, :method => :get do %>
    <p>
    <%= label_tag 'mobile', '手機' %>
    <%= text_field_tag 'mobile' %>
    </p>
    <%= submit_tag '查詢', :class => 'btn btn-action' %>
  <% end %>
</div>
<div class="row">
  <% @orders.each do |order| %>
    <table class="table table-striped table-bordered table-condensed">
      <caption>
        領取日:<%= order.draw_date.to_s[0] %>/<%= order.draw_date.to_s[1..-1] %> |
        總價: <%= order.total_price %>
    </caption>
    <tr>
      <th>名稱</th>
      <th>數量</th>
      <th>單價</th>
      <th>小計</th>
    </tr>
    <% order.order_itemships.each do |o_i| %>
      <tr>
        <td>
          <%= link_to o_i.item.name, item_path(o_i.item) %>
        </td>
        <td>
          <%= o_i.count %>
        </td>
        <td>
          <%= o_i.item.price %>
        </td>
        <td>
          <%= o_i.item.price.to_i * o_i.count.to_i %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>
</div>

app/views/pages/notice.html.erb
<div class="span9" style="margin-top:30px;">
  <h4>
    <p class="notice-title">
      【預購網站怎麼用?】
    </p>
  </h4>
  <p>
  <span class="notice-step">
    Step1
  </span>
    眼明手快地點選想要的商品，選取數量，按下加入購物車
  </p>
  <p>
  <span class="notice-step">
  Step2
  </span>
  買完所有商品之後，按下查看購物車
  </p>
  <p>
  <span class="notice-step">
  Step3
  </span>
  別忘了在購物車下面打上基本資料：姓名、手機、信箱
  </p>
  <p>
  <span class="notice-step">
    Step4
  </span>
  選擇想要領預購商品的日期，可選擇黃道吉日5/15(星期三)或 5/16(星期四)
  </p>
  <p>
  <span class="notice-step">
    Step5
  </span>
  按下建立訂單之後，就完成網路預購手續了喔！之後，你可以生生不息地隨時透過本網站的「查詢訂單」功能，一邊擦口水一邊回想自己訂了什麼商品。
  </p>
  <p>預購網站開放時間4/12~5/5</p>
  <h4>
    <p class="notice-title">
    【我該怎麼繳費】
    </p>
  </h4>
  <p>
  <b>
    5/6 或 5/7中午12:15~14:30，請選擇一天，到博雅教學館靠近小福樓、醉月湖的空地，會有竹友會的工作人員在那裡收費。收費時會一併發放收據，請悉心珍藏，以供領貨時使用。
  </b><br />
  繳費位置示意圖：<br /><%= image_tag "https://dl.dropboxusercontent.com/u/106261618/Payment.jpg" %>
  </p>
  繳費前一天，我們會拋頭露面不計形象地發簡訊通知大家繳費訊息，請大家務必要記得繳費喔，不然訂單就會被取消了餒，一定要記得喔！
  <p>
  </p>
  <h4>
    <p class="notice-title">
    【快把我的食物給我─我該如何領預購商品】
    </p>
  </h4>
  <p>
    <b>
      請在自己選擇的時間(5/15或5/16)，中午12:30~16:00持收據到竹塹週小福攤位領取「預購商品」。
    </b>
  </p>
  <p>
  為了確保食物新鮮，我們統計完大家填寫的時間之後，會請廠商分兩天送達，所以一定要在自己選的那天來攤位領貨喔，以免向隅！
  </p>
  <p>
  領貨前一天，我們一樣會出神入化地用簡訊通知大家，請大家放心。
  </p>
  <p>
 看完那麼三八的預購須知，想必你已經蠢蠢欲動想要開始預購了吧。如果有什麼問題，歡迎在竹塹週FB粉絲專頁反映，我們會分秒必爭地回覆你喔，謝謝！
 <%= link_to '竹塹週FB粉絲專頁', 'https://www.facebook.com/EatMe2013BambooWeek' %>
  </p>
</div>